Repository BC-MAY-21-ROR/kata-07-reloj-checador-k7-f22-t2, pull requests merged in 2022-04, with the labels that each got.

#32 Add check out logic for the employee
  app/controllers/home_controller.rb
Labels: mentor review required, ready for review, review required

#31 Feature#30/crud branch
  app/assets/stylesheets/pages/_administration_view.scss
  app/controllers/branch_controller.rb
  app/controllers/branches_controller.rb
  app/controllers/street_cps_controller.rb
  app/helpers/admin_helper.rb
  app/helpers/application_helper.rb
  app/helpers/branch_helper.rb
  app/helpers/employee_helper.rb
  app/helpers/home_helper.rb
  app/models/branch.rb
  app/models/street_cp.rb
  app/views/branches/_form.html.erb
  app/views/branches/edit.html.erb
  app/views/branches/index.html.erb
  app/views/branches/new.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/employees/index.html.erb
  app/views/street_cps/new.html.erb
  config/routes.rb
  db/migrate/20220311003928_create_branches.rb
  db/schema.rb
  test/controllers/branches_controller_test.rb
  test/fixtures/branches.yml
  test/system/branches_test.rb
Labels: mentor review required, ready for review, review required

#38 Add view for reports information
  app/controllers/employees_controller.rb
  app/views/employees/report.html.erb
  config/routes.rb
  db/migrate/20220311003928_create_branches.rb
  db/schema.rb
Labels: mentor review required, ready for review, review required

#39 Added logic to count absences
  app/models/employee.rb
  app/views/employees/report.html.erb
Labels: ready for review, review required

#40 Create model method to return the assistance of the day
  app/models/employee.rb
  app/views/employees/report.html.erb
Labels: mentor review required, ready for review, review required

#41 Create model method to obtain average clock_in and clock_out
  app/models/employee.rb
  app/views/employees/report.html.erb
Labels: mentor review required, ready for review

#42 Add hamburger menu
  app/assets/stylesheets/base/_globals.scss
  app/assets/stylesheets/layout/_header.scss
  app/javascript/hamburger-menu.js
  app/views/layouts/_header.html.erb
  app/views/layouts/application.html.erb
Labels: mentor review required, ready for review, review required
